name: CI
on:
  push:
    branches:
      - main
  pull_request: 
jobs:
  build-image:
    name: Build Godot image
    uses: ./.github/workflows/build-image.yaml
  run-checks:
    name: Run Godot project checks
    needs: build-image
    uses: ./.github/workflows/run-checks.yaml
  release-export:
    runs-on: ubuntu-22.04
    steps:
      - name: 
    