name: CI
on:
  push:
    branches:
      - main
  pull_request: 
jobs:
  build-image:
    name: Build Godot image
    uses: ./.github/workflows/build-image.yaml
  run-checks:
    name: Run Godot project checks
    uses: ./.github/workflows/run-checks.yaml
    